### ISSUE TITLE
`navigator.loadHtml` not working

### ISSUE THREAD

**Issue by andreaseveri** [KevinnZou/compose-webview#13]
As previously stated [here](https://github.com/KevinnZou/compose-webview-multiplatform/issues/62), `navigator.loadHtml` does not work correctly, 'cause of the wrong order of parameters.

**Comment by KevinnZou** [comment]
@andreaseveri Thanks for your feedback! I took a quick look and it seems that the parameter order in this library is correct. Could you please attach the test code so that I can test it tomorrow?

**Comment by andreaseveri** [comment]
I tried [this example](https://github.com/google/accompanist/pull/1557#issue-1638840836) from an Accompanist PR, replacing `loadUrl` with `loadHtml`, but html is never loaded.

**Comment by KevinnZou** [comment]
@andreaseveri Could you provide the simplest reproducible sample? I tested it locally with the following code and it worked well.
```
val html = """
        <html>
            <body>
                <h1>Hello, World!</h1>
            </body>
        </html>
    """.trimIndent()
```

**Comment by andreaseveri** [comment]
After testing it a lot, I can confirm the issue was on my end.
