### ISSUE TITLE
WebViewState does not have WebSettings variable

### ISSUE THREAD

**Issue by SnowCharmQ** [KevinnZou/compose-webview#3]
As the title says, the WebViewState class does not have a variable called webSettings as an object of the WebSettings class. The README file has an error.
![image](https://github.com/KevinnZou/compose-webview/assets/82224175/dd4f74cc-a80a-4160-84d2-4120c56e146a)

**Comment by KevinnZou** [comment]
@SnowCharmQ Thanks for your feedback! Yes, you are correct. I simply copied it from my multiplatform version of this library. I apologize for any inconvenience caused and I will fix it soon.
