### ISSUE TITLE
Webview Background color

### ISSUE THREAD

**Issue by Adarsh098765** [KevinnZou/compose-webview#4]
I am trying to change the background color of the webview using modifier but it not working.

 val content = pageData?.PageContent.toString()
 val webViewState = rememberWebViewStateWithHTMLData(data = content)
 WebView(modifier = Modifier.background(color = AppCardBackground),state = webViewState, onCreated = { it.settings.javaScriptEnabled = true }, captureBackPresses = false, )

**Comment by KevinnZou** [comment]
@Adarsh098765 Thanks for your feedback! Since we are using AndroidView to wrap the WebView, modifier.background will not have effect. To change the background color of the webview, please use the `webview.setBackgroundColor` in the onCreated block.

**Comment by Adarsh098765** [comment]
val content = pageData?.PageContent.toString()
            val webViewState = rememberWebViewStateWithHTMLData(data = content)
            WebView(
                state = webViewState,
                onCreated = {
                    it.settings.javaScriptEnabled = true
                    it.background = context.getDrawable(R.color.purple_200)
                },
                captureBackPresses = false,
            )

Not working
